<div id="accordion" data-mage-init='{"nav.accordion": {}}'>
    <div data-role="collapsible">
        <h2 data-role="trigger"><?= $block->escapeHtml(__('Links')) ?> </h2>
    </div>
    <ul data-role="content">
        <li><a href="<?=$block->escapeUrl($block->getBaseUrl()); ?>"> <?= $block->escapeHtml(__('Nav1')) ?> </a></li>
        <li><a href="<?=$block->escapeUrl($block->getBaseUrl()); ?>"> <?= $block->escapeHtml(__('Nav2')) ?> </a></li>
        <li><a href="<?=$block->escapeUrl($block->getBaseUrl()); ?>"> <?= $block->escapeHtml( __('Nav3')) ?> </a></li>
        <li><a href="<?=$block->escapeUrl($block->getBaseUrl()); ?>"> <?= $block->escapeHtml(__('Nav4')) ?> </a></li>
        <li><a href="<?=$block->escapeUrl($block->getBaseUrl()); ?>"> <?= $block->escapeHtml(__('Nav5')) ?> </a></li>
    </ul>
    <div data-role="collapsible">
        <h2 data-role="trigger"><?= $block->escapeHtml(__('Links2')) ?> </h2>
    </div>
    <ul data-role="content">
        <li><a href="<?=$block->escapeUrl($block->getBaseUrl()); ?>"> <?= $block->escapeHtml(__('Nav6')) ?> </a></li>
        <li><a href="<?=$block->escapeUrl($block->getBaseUrl()); ?>"> <?= $block->escapeHtml(__('Nav7')) ?> </a></li>
        <li><a href="<?=$block->escapeUrl($block->getBaseUrl()); ?>"> <?= $block->escapeHtml( __('Nav8')) ?> </a></li>
        <li><a href="<?=$block->escapeUrl($block->getBaseUrl()); ?>"> <?= $block->escapeHtml(__('Nav9')) ?> </a></li>
        <li><a href="<?=$block->escapeUrl($block->getBaseUrl()); ?>"> <?= $block->escapeHtml(__('Nav10')) ?> </a></li>
    </ul>
    <div data-role="collapsible">
        <h2 data-role="trigger"><?= $block->escapeHtml(__('Links3')) ?> </h2>
    </div>
    <ul data-role="content">
        <li><a href="<?=$block->escapeUrl($block->getBaseUrl()); ?>"> <?= $block->escapeHtml(__('Nav11')) ?> </a></li>
        <li><a href="<?=$block->escapeUrl($block->getBaseUrl()); ?>"> <?= $block->escapeHtml(__('Nav12')) ?> </a></li>
        <li><a href="<?=$block->escapeUrl($block->getBaseUrl()); ?>"> <?= $block->escapeHtml( __('Nav13')) ?> </a></li>
        <li><a href="<?=$block->escapeUrl($block->getBaseUrl()); ?>"> <?= $block->escapeHtml(__('Nav14')) ?> </a></li>
        <li><a href="<?=$block->escapeUrl($block->getBaseUrl()); ?>"> <?= $block->escapeHtml(__('Nav15')) ?> </a></li>
    </ul>
</div>
